version: "3.7"

services:
  # backend:
  #   build: ./
  #   container_name: cl-backend
  #   volumes:
  #     - ./:/usr/src/app
  #   ports:
  #     - 4000:4000
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  #   restart: always
  mysql:
    image: mysql:5
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_USER: cltest
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql:
